default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: decision_service_production
  username: ubuntu

test:
  <<: *default
  database: decision_service_test

production:
  <<: *default
  database: decision_service_production
  username: ubuntu
  password: <%= ENV['DECISION_SERVICE_DATABASE_PASSWORD'] %>
